const { LicensedUser, User } = require('../models');

// Generate enhanced PDF report with student details and coding results
async function generateEnhancedPDFReport(test, testSessions, codingResultsMap, res) {
  const PDFDocument = require('pdfkit');
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  
  // Set headers for PDF download
  const filename = `${test.name.replace(/[^a-zA-Z0-9]/g, '_')}_Complete_Report.pdf`;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  
  // Pipe PDF to response
  doc.pipe(res);
  
  // Header
  doc.fontSize(20).text('TEST RESULT REPORT', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(2);
  
  // Test Information
  doc.fontSize(16).text('TEST INFORMATION', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12)
     .text(`Test Name: ${test.name}`)
     .text(`Test ID: ${test.testId}`)
     .text(`Description: ${test.description || 'N/A'}`)
     .text(`Total Participants: ${testSessions.length}`);
  
  doc.moveDown(2);
  
  // Process each student
  for (let i = 0; i < testSessions.length; i++) {
    const session = testSessions[i];
    
    // Check if we need a new page
    if (doc.y > 650) {
      doc.addPage();
    }
    
    // Get student details - prioritize LicensedUser
    let student = await LicensedUser.findByPk(session.studentId, {
      attributes: ['name', 'email', 'department']
    });
    
    if (!student) {
      student = await User.findByPk(session.studentId, {
        attributes: ['name', 'email', 'sinNumber', 'department']
      });
    }
    
    const percentage = session.maxScore > 0 ? Math.round((session.totalScore / session.maxScore) * 100) : 0;
    const timeTaken = session.completedAt && session.startedAt ? 
      Math.round((new Date(session.completedAt) - new Date(session.startedAt)) / (1000 * 60)) : 0;
    
    // Student header
    doc.fontSize(14).text(`${i + 1}. STUDENT INFORMATION`, { underline: true });
    doc.moveDown(0.3);
    
    // Student information
    doc.fontSize(11)
       .text(`Name: ${student?.name || 'N/A'}`)
       .text(`Email: ${student?.email || 'N/A'}`)
       .text(`Department: ${student?.department || 'N/A'}`)
       .text(`SIN Number: ${student?.sinNumber || 'N/A'}`);
    
    doc.moveDown(0.5);
    
    // Test performance
    doc.fontSize(12).text('Test Performance:', { underline: true });
    doc.fontSize(11)
       .text(`Score: ${session.totalScore}/${session.maxScore} (${percentage}%)`)
       .text(`Status: ${percentage >= 60 ? 'Pass' : 'Fail'}`)
       .text(`Time Taken: ${timeTaken} minutes`)
       .text(`Completed At: ${new Date(session.completedAt).toLocaleString()}`);
    
    // Coding results if available
    const codingResults = codingResultsMap[session.studentId] || [];
    if (codingResults.length > 0) {
      doc.moveDown(0.5);
      doc.fontSize(12).text('Coding Results:', { underline: true });
      
      codingResults.forEach((coding, codingIndex) => {
        doc.fontSize(11)
           .text(`Language: ${coding.language}`)
           .text(`Status: ${coding.status}`)
           .text(`Score: ${coding.score} points`);
        
        if (coding.testResults && Array.isArray(coding.testResults)) {
          const passedTests = coding.testResults.filter(t => t.passed).length;
          const totalTests = coding.testResults.length;
          doc.text(`Test Cases: ${passedTests}/${totalTests} passed`);
        }
        
        if (codingIndex < codingResults.length - 1) {
          doc.moveDown(0.3);
        }
      });
    }
    
    doc.moveDown(1);
    
    // Add separator line
    if (i < testSessions.length - 1) {
      doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(0.5);
    }
  }
  
  // Footer
  doc.fontSize(10)
     .text('Report generated by MCQ Assessment Platform', 40, 750, { align: 'center' });
  
  // Finalize PDF
  doc.end();
}

module.exports = { generateEnhancedPDFReport };