const { Test, TestSession, User, LicensedUser } = require('../models');

class SimpleReportGenerator {
  
  // Generate simple text-based report
  static async generateSimpleTestReport(testId, res) {
    try {
      // Get test data
      const test = await Test.findOne({
        where: { testId },
        attributes: ['testId', 'name', 'description', 'createdAt']
      });

      if (!test) {
        return res.status(404).json({
          success: false,
          message: 'Test not found'
        });
      }

      // Get test sessions
      const testSessions = await TestSession.findAll({
        where: { testId, status: 'completed' },
        attributes: ['id', 'studentId', 'totalScore', 'maxScore', 'startedAt', 'completedAt'],
        order: [['totalScore', 'DESC']]
      });

      // Generate report content
      let reportContent = `TEST ASSESSMENT REPORT\n`;
      reportContent += `========================\n\n`;
      reportContent += `Test Name: ${test.name}\n`;
      reportContent += `Test ID: ${test.testId}\n`;
      reportContent += `Description: ${test.description || 'N/A'}\n`;
      reportContent += `Report Generated: ${new Date().toLocaleString()}\n`;
      reportContent += `Total Participants: ${testSessions.length}\n\n`;

      if (testSessions.length > 0) {
        // Calculate statistics
        const scores = testSessions.map(s => s.maxScore > 0 ? (s.totalScore / s.maxScore) * 100 : 0);
        const averageScore = scores.reduce((a, b) => a + b, 0) / scores.length;
        const passedStudents = scores.filter(s => s >= 60).length;
        const highestScore = Math.max(...scores);

        reportContent += `PERFORMANCE STATISTICS\n`;
        reportContent += `======================\n`;
        reportContent += `Average Score: ${Math.round(averageScore)}%\n`;
        reportContent += `Pass Rate: ${Math.round((passedStudents/testSessions.length)*100)}%\n`;
        reportContent += `Highest Score: ${Math.round(highestScore)}%\n`;
        reportContent += `Passed Students: ${passedStudents}/${testSessions.length}\n\n`;

        reportContent += `DETAILED RESULTS\n`;
        reportContent += `================\n`;
        reportContent += `Rank | Student Name          | Score     | Percentage | Status\n`;
        reportContent += `-----|----------------------|-----------|------------|-------\n`;

        // Add student results
        for (let i = 0; i < testSessions.length; i++) {
          const session = testSessions[i];
          
          // Get student details
          let student = await LicensedUser.findByPk(session.studentId, {
            attributes: ['name', 'email']
          });
          
          if (!student) {
            student = await User.findByPk(session.studentId, {
              attributes: ['name', 'email']
            });
          }
          
          const percentage = session.maxScore > 0 ? Math.round((session.totalScore / session.maxScore) * 100) : 0;
          const status = percentage >= 60 ? 'Pass' : 'Fail';
          const studentName = (student?.name || 'Unknown').padEnd(20).substring(0, 20);
          const scoreText = `${session.totalScore}/${session.maxScore}`.padEnd(9);
          const percentText = `${percentage}%`.padEnd(10);
          
          reportContent += `${String(i + 1).padStart(4)} | ${studentName} | ${scoreText} | ${percentText} | ${status}\n`;
        }
      } else {
        reportContent += `No completed test sessions found.\n`;
      }

      reportContent += `\n\nReport generated by MCQ Assessment Platform\n`;
      reportContent += `Generated on: ${new Date().toLocaleDateString()}\n`;

      // Set headers for text download
      const filename = `${test.name.replace(/[^a-zA-Z0-9]/g, '_')}_Report.txt`;
      res.setHeader('Content-Type', 'text/plain');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      
      res.send(reportContent);
      
    } catch (error) {
      console.error('Error generating simple report:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to generate report: ' + error.message
      });
    }
  }

  // Generate JSON report for API consumption
  static async generateJSONReport(testId, res) {
    try {
      const test = await Test.findOne({
        where: { testId },
        attributes: ['testId', 'name', 'description', 'createdAt']
      });

      if (!test) {
        return res.status(404).json({
          success: false,
          message: 'Test not found'
        });
      }

      const testSessions = await TestSession.findAll({
        where: { testId, status: 'completed' },
        order: [['totalScore', 'DESC']]
      });

      const results = [];
      
      for (let i = 0; i < testSessions.length; i++) {
        const session = testSessions[i];
        
        let student = await LicensedUser.findByPk(session.studentId, {
          attributes: ['name', 'email', 'department']
        });
        
        if (!student) {
          student = await User.findByPk(session.studentId, {
            attributes: ['name', 'email']
          });
        }
        
        const percentage = session.maxScore > 0 ? Math.round((session.totalScore / session.maxScore) * 100) : 0;
        
        results.push({
          rank: i + 1,
          studentId: session.studentId,
          studentName: student?.name || 'Unknown',
          email: student?.email || 'N/A',
          department: student?.department || 'N/A',
          score: session.totalScore,
          maxScore: session.maxScore,
          percentage,
          status: percentage >= 60 ? 'Pass' : 'Fail',
          completedAt: session.completedAt
        });
      }

      // Calculate statistics
      const totalStudents = results.length;
      const passedStudents = results.filter(r => r.status === 'Pass').length;
      const averageScore = totalStudents > 0 ? 
        Math.round(results.reduce((sum, r) => sum + r.percentage, 0) / totalStudents) : 0;

      const report = {
        test: {
          testId: test.testId,
          name: test.name,
          description: test.description,
          createdAt: test.createdAt
        },
        statistics: {
          totalStudents,
          passedStudents,
          failedStudents: totalStudents - passedStudents,
          passRate: totalStudents > 0 ? Math.round((passedStudents / totalStudents) * 100) : 0,
          averageScore
        },
        results,
        generatedAt: new Date().toISOString()
      };

      res.json({
        success: true,
        report
      });
      
    } catch (error) {
      console.error('Error generating JSON report:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to generate report: ' + error.message
      });
    }
  }
}

module.exports = SimpleReportGenerator;